### ISSUE TITLE
 프로젝트 참가 신청 수락 에러

### ISSUE THREAD

**Issue by younchong** [project-matching/project-matching-backend#123]
# /v1/participate/{projectParticipateNo}/permit

500 에러가 떠서 확인 부탁드립니다.

## 터미널 

<img width="1021" alt="스크린샷 2022-09-20 오후 2 26 59" src="https://user-images.githubusercontent.com/78673049/191174620-72332ebd-e021-4bc9-9823-7d4f20a225b4.png">

# post man으로 api 요청 보낸 후 response

<img width="898" alt="스크린샷 2022-09-20 오후 2 27 27" src="https://user-images.githubusercontent.com/78673049/191174682-f7bc2e8d-45df-49b1-be8b-2a00a6da1ed1.png">

**Comment by leeworld9** [comment]
수정 완료하였고, @younchong 님과 동작확인 까지 완료하였습니다.
