### ISSUE TITLE
차단된 OAuth 유저의 에러 메세지 전송

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#128]
- OAuth 유저가 차단되었을 경우 클라이언트에서 에러 메세지를 받지 못하고 있습니다.
- 클라이언트로 리다이렉팅되지 않는 상태입니다.
- status code: 500

**Comment by leeworld9** [comment]
@Olivia-SY129 @younchong 

- #128 이슈 수정
    - 일반적인 경우와 다르게 해당 상황에서는 리다이렉팅으로만 프론트에 전달 가능했기 때문에 아래와 같은 방법으로 프론트로 전달 했습니다. (해결방법을 찾으면 수정 예정)
         ```
         http://localhost:3000/auth/fail?reason=block
         http://localhost:3000/auth/fail?reason=withdrawal
         ```
- 프로필에 따라서 프론트 주소가 변경되도록 수정
     - prod : http://ec2-3-37-7-111.ap-northeast-2.compute.amazonaws.com:3000
     - local, dev : http://localhost:3000

**Comment by leeworld9** [comment]
늦어져서 죄송합니다. 개인적인 사정으로  **22.11.18일(금)** 까지 대응할일이 있어서 처리가 늦어졌네요. 아마 18일까지는 이슈처리가 조금 힘들듯 합니다. 그동안 이슈 생기시면 깃허브에 이슈 달아 주세요. 주말에 가능한 최대한 처리해보겠습니다!!!
