### ISSUE TITLE
user-controller 에러 처리

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#40]
엔드포인트: /v1/user/info 
위 API를 JWT 토큰 없이 요청했을 경우 로그인 화면으로 리다이렉트하는 대신 에러 처리로 변경해주세요.

**Comment by leeworld9** [comment]
#46 에서 해당 사항 반영하였습니다.

**Comment by Olivia-SY129** [comment]
감사합니다. 다음부터 반영 완료된 이슈는 닫아주셔도 됩니다. :)
