### ISSUE TITLE
email 인증 메일의 URL 주소 클라이언트로 변경 요망

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#41]
1. 모든 인증 메일(회원가입, 비밀번호 변경)의 URL를 클라이언트 오리진으로 변경해주세요.
2. 해당 인증 메일의 파라미터를 전송할  REST API 엔드포인트 및 메서드를 알려주세요.

**Comment by leeworld9** [comment]
1. URL은 클라이언트 주소로 변경하였으나 현재 develop 브런치에는 아직 반영이 안되어있습니다. 다음 풀리퀘때 반영할 예정입니다.

2. 
```
메일 인증 (POST) : /v1/user/confirm (email, authToken 필요)
비밀번호 초기화 (PATCH) : /v1/common/password/confirm (email, password, authToken 필요)
```

**Comment by leeworld9** [comment]
#46 에서 해당 사항 반영하였습니다.

**Comment by Olivia-SY129** [comment]
감사합니다.
