### ISSUE TITLE
회원 정보 요청 시 올바르지 않은 이미지 값 응답

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#69]
- 이미지 값이 url 이 아닌 형식의 값을 응답

```json
{
    "error": null,
    "data": {
        "name": "user1",
        "sex": "N",
        "email": "user1@test.com",
        "position": null,
        "loginCategory": "NORMAL",
        "technicalStackList": [],
        "github": null,
        "selfIntroduction": null,
        "image": "default_url"
    }
}
```

**Comment by leeworld9** [comment]
@Olivia-SY129
- 현재 이미지가 등록되어 있지 않으면 디폴트 이미지 URL이 들어가게 수정되었는데, 디폴트 이미지가 정해지지 않아서 `default_url`이라는 String으로 넘기고 있습니다. 해당부분은 이미지가 정해지면 수정될 예정입니다.

**Comment by Olivia-SY129** [comment]
> @Olivia-SY129
> 
> * 현재 이미지가 등록되어 있지 않으면 디폴트 이미지 URL이 들어가게 수정되었는데, 디폴트 이미지가 정해지지 않아서 `default_url`이라는 String으로 넘기고 있습니다. 해당부분은 이미지가 정해지면 수정될 예정입니다.

확인했습니다.
