### ISSUE TITLE
유저 프로필 수정 데이터 형식

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#78]
endpoint: (PATCH) /user
- 머지하신 부분 postman으로 시도해보았는데, 요청이 잘못된 것 같습니다. 어디에서 문제가 발생한 건가요?

![image](https://user-images.githubusercontent.com/81205807/185825294-071e56a1-c572-46a1-892f-65a28de3e738.png)

**Comment by leeworld9** [comment]
폼 데이터 입력 시 문자열을 "N"이 아니라 N과 같은 형식으로 입력해주시기 바랍니다.
