### ISSUE TITLE
기술스택 리스트 접근 Fobidden

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#79]
## Issue
기술스택 리스트 일반 유저 접근 불가
- 프로필 정보 변경 페이지에서 기술 스택 리스트 필요

## Endpoint
(GET) /technicalStack

## 안건
- 일반 유저인 경우 접근이 불가능한데, 가능하게 변경해주실 수 있나요?

**Comment by wkemrm** [comment]
GET /v1/technicalStack 권한을 기존의 어드민에서 (유저, 어드민)으로 변경했습니다.

- @Olivia-SY129, @younchong
