### ISSUE TITLE
이미지 주소 문자열 형식

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#80]
## Issue
이미지 주소가 URL이 아닌 일반 문자열 `default_image`으로 응답
- 해당 문자열로 프론트엔드에 불필요한 코드 증가
- 테스트가 끝나셨다면 이미지 문자열은 URL 또는 빈 문자열로 보내주시면 좋을 것 같습니다.

**Comment by leeworld9** [comment]
디폴트 이미지로 사용할 이미지를 지정해주시면, 다음 풀리퀘 부터 반영시키도록 하겠습니다.

**Comment by Olivia-SY129** [comment]
> 디폴트 이미지로 사용할 이미지를 지정해주시면, 다음 풀리퀘 부터 반영시키도록 하겠습니다.

기술 스택의 경우, 공식 사이트의 이미지를 사용하시면 될 것 같습니다. 그 외 또 필요한 이미지가 있다면 말씀해주세요.

**Comment by leeworld9** [comment]
아, 여기서 말씀드린 디폴트 이미지는 이미지가 등록이 되지 않았을때 표시되는 이미지를 의미합니다.

**Comment by Olivia-SY129** [comment]
> 일단 논의한대로 이미지가 없는경우 예전과 동일하게 null 로 입력하도록 수정하겠습니다.

넵! 수정하시면 머지할때 저 태그 달아주세요.
