### ISSUE TITLE
유저 탈퇴 관련 이슈

### ISSUE THREAD

**Issue by leeworld9** [project-matching/project-matching-backend#82]
- 현재 `일반 유저`든 `소셜 유저`든 탈퇴 시 해당 이메일로 재가입이 불가능함.
- `소셜 유저`은 기존 소셜계정의 이메일을 변경하는것이 불가능한데 재가입이 불가능하게 해야하는게 맞는건지 논의가 필요.

**Comment by wkemrm** [comment]
일반 유저 및 소셜 유저가 탈퇴를 할 경우 기존 유저가 속해 있던 모든 프로젝트, 북마크, 알림, 프로젝트 포지션, 유저 기술 스택, 프로젝트 신청, 프로젝트 신청 기술스택을 삭제하고, users table의 withdrawal을 true로 바꾸는 것으로 논의하였다.
1. 회원 탈퇴시 자신이 만든 프로젝트에 속한 유저들에게 알림이 필요하다.
2. 기존 댓글 조회를 할때 탈퇴한 유저의 댓글은 user의 fk를 null로 바꾸고 프론트에서 null일 경우 탈퇴한 유저라고 표시한다.
3. 6개월에 한번씩 withdrawal column이 true인 raw는 일괄 삭제한다.
4. 일반 유저의 경우 같은 email의 경우에는 재가입이 불가능하다.
5. 소셜 유저의 경우 같은 로그인 정보일 경우에는 재가입이 불가능하다.
