### ISSUE TITLE
알림 목록 조회 시 응답 값 형식

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#90]
## Issue
- 알림 목록 조회 시 응답 값 중 `data.content.type`의 타입 종류가 `NOTICE` 외 어떤 것이 있는지 알 수 있을까요?

## Endpoint
(GET) /notification

```
{
  "data": {
    "content": [
      {
        "createDate": "2022-08-24T04:33:29.384Z",
        "no": 0,
        "read": true,
        "title": "string",
        "type": "NOTICE"
      }
    ],
    "last": true
  },
  "error": {
    "code": "string",
    "error": "string",
    "message": [
      "string"
    ],
    "status": 0,
    "timestamp": "2022-08-24T04:33:29.384Z"
  }
}
```

**Comment by leeworld9** [comment]
공지사항입니다!

**Comment by leeworld9** [comment]
- NOTICE : 공지사항
- PROJECT_DELETE : 프로젝트 삭제
- PROJECT_PARTICIPATION_REQUEST : 프로젝트 참가 요청
- PROJECT_PARTICIPATION_SUCCESS : 프로젝트 참가 성공
- PROJECT_PARTICIPATION_REFUSE : 프로젝트 참가 거절
- PROJECT_POSITION_EXPULSION : 프로젝트 추방
- PROJECT_POSITION_WITHDRAW : 프로젝트 탈퇴

**Comment by wkemrm** [comment]
$.data.content.no를 $.data.content.notificationNo로 변경 완료했습니다.
