### ISSUE TITLE
Refresh token 개선 가능 여부

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-backend#96]
## 안건
- refresh 토큰의 정확한 동작 로직
- 현재 토큰은 만료 기한을 클라이언트에서 알 수 없기 때문에 불필요한 API를 요청해야 할 경우가 생김

## Reference
<a href='https://han-um.tistory.com/17'>JWT의 개념, 프론트엔드에서 해야 할 일</a>

**Comment by leeworld9** [comment]
현재 만료기한 관련해서는 프론트쪽에 보내는데 별 어려움은 없습니다.  나중에 프론트쪽에서 확인후에 풀리퀘 할 예정입니다.

**Comment by leeworld9** [comment]
- #102 : 반영해서 머지 완료하였습니다.
